/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.preguntaventanas;

import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author CDMFP
 */
public class Pantalla extends javax.swing.JFrame {
static ArrayList<Pregunta> lista_preguntas=null;//La hago global porque necesito que otros métodos la vean
static int indice_pregunta=0;//La hago global porque necesito que otros métodos la vean
static int puntuacion=0;//La hago global porque necesito que otros métodos la vean    
/**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_textopregunta = new javax.swing.JLabel();
        txt_respuesta = new javax.swing.JTextField();
        lbl_puntuacion = new javax.swing.JLabel();
        btn_comprobar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_textopregunta.setText("jLabel1");

        txt_respuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_respuestaKeyPressed(evt);
            }
        });

        lbl_puntuacion.setText("0");

        btn_comprobar.setText("Comprobar");
        btn_comprobar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_comprobarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_textopregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_comprobar)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_puntuacion)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_puntuacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_textopregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_comprobar))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_comprobarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_comprobarMouseClicked
        // TODO add your handling code here:
        comprobarRespuesta();
       
    }//GEN-LAST:event_btn_comprobarMouseClicked
private void comprobarRespuesta()
{
     String respuesta_usuario=txt_respuesta.getText();
        Pregunta p=lista_preguntas.get(indice_pregunta);
        String respuesta_correcta=p.getTexto_respuesta();
        if (respuesta_correcta.equals(respuesta_usuario))
        {
            puntuacion++;
            JOptionPane.showMessageDialog(rootPane, "Enhorabuena");
            actualizarPuntuacion();
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, 
                    "Has fallado, la respuesta es:"+respuesta_correcta);
        }
        if (indice_pregunta<lista_preguntas.size()-1)
        {
        indice_pregunta++;
        mostrarPregunta();
        }
        else
        {
            //Fin juego
            //accionesFinJuego();
            JOptionPane.showMessageDialog(rootPane, 
                    "Enghorabuena y gracias por jugar");
        }
}
    private void txt_respuestaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_respuestaKeyPressed
        // TODO add your handling code here:
        int tecla=evt.getKeyCode();
        long l=evt.getWhen();
        System.out.println(l);
        if (tecla==10)
        {
            comprobarRespuesta();
        }
    }//GEN-LAST:event_txt_respuestaKeyPressed

    /**
     * @param args the command line arguments
     */
    private static void actualizarPuntuacion()
    {
        lbl_puntuacion.setText(String.valueOf(puntuacion));
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        lista_preguntas=AccesoFichero.recuperarPreguntas();
       
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
                 mostrarPregunta();//En el label de pregunta saca el texto de la pregunta que toque
            }
        });
    }
    private static void mostrarPregunta()
    {
        Pregunta p=lista_preguntas.get(indice_pregunta);
        String texto_pregunta=p.getTexto_pregunta();
        lbl_textopregunta.setText(texto_pregunta);
        txt_respuesta.setText("");
        txt_respuesta.requestFocusInWindow();
    }
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btn_comprobar;
    private static javax.swing.JLabel lbl_puntuacion;
    private static javax.swing.JLabel lbl_textopregunta;
    private static javax.swing.JTextField txt_respuesta;
    // End of variables declaration//GEN-END:variables
}
